# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
connection: &connection
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: denis

development:
  <<: *connection
  database: stat_dev

test:
  <<: *connection
  database: stat_test

production:
  <<: *connection
  database: stat_prod

